### ISSUE TITLE
RealmManager.localInstance is closed after calling openLocalInstance

### ISSUE THREAD

**Issue by fvink** [Zhuinden/realm-helpers#10]
Hi Zhuinden!

I have the RealmManager defined as Kotlin's `object` class and I'm using it inside repositories like this (shortened code): 

```
class RealmRepository {
    protected val realm: Realm
        get() = RealmManager.localInstance

    override fun add(item: T): T {
        return realm.copyToRealm(item)
    }
}
```

`RealmManager.openLocalInstance` is called in the activity's `onCreate` and the instance is opened and set to `RealmManager.localRealms` field. Realm is initialized in `Application.onCreate`.

**The issue:**
In onResume the repository's method is called and the RealmManager.localInstance is accessed but it is closed. This is all done on the same (main) thread. `closeLocalInstance` is only invoked in `activity.onDestroy`.

However, this only happens after a clean install or when the app data is cleared. After that the Realm instance is not being closed even after killing the app and restarting it, and the code works fine.

**Comment by fvink** [comment]
The app did actually close the Realm instance at a different place in code which was accidentally left over.

**Comment by Zhuinden** [comment]
I forgot to reply, but I'm glad you've found the source of the issue
