### ISSUE TITLE
[realm-singleton-manager-example] How to use RealmManager inside DbHelper/DbService?

### ISSUE THREAD

**Issue by Drjacky** [Zhuinden/realm-helpers#5]
Currently, you're writing all of your DB queries inside the MainActivity; Like:
```
private void setupBookView() {
        Realm realm = realmManager.getLocalInstance();
        RealmResults result = realm.allObjects(Book.class);
...
}
```
But I want something like this:
```
private void setupSampleView() {
        RealmResults result = mDbService.getAllBooks();
...
}
```
__________________________________________________________________________
How to use RealmManager inside DbService? Is this approach correct? :

**IDbService.java:**
```
public interface IDbService{
    RealmResults<Book> getAllBooks(final Realm realm);
}
```
**DbService.java:**
```
public class DbService implements IDbService {
    public DbService() {
   //nothing is here.
    }

    @Override
    public RealmResults<Book> getAllBooks(final Realm realm) {
        return realm.allObjects(Book.class);
    }
}
```
**IDataManager.java:**
```
public interface IDataManager extends IDbService {
    @Override
    RealmResults<Book> getAllBooks(final Realm realm);
}
```
**DataManager.java:**
```
public class DataManager implements IDataManager{
    private final Context mContext;
    private final IDbService mDbService;

    @Inject
    public DataManager(@ApplicationContext Context context,
                          IDbService dbService) {
        mContext = context;
        mDbService = dbService;
    }

    @Override
    public RealmResults<Book> getAllBooks(final Realm realm); {
        return mDbService .getAllBooks(realm);
    }
}
```
**DataModule.java:**
```
@Module
public class DataModule {

    @Provides
    @Singleton //I'm not sure about @Singleton or @PerActivity annotation here.
    IDbService provideIDbService(DbService dbService){
        return DbService;
    }

    @Provides
    @Singleton //I'm not sure about @Singleton or @PerActivity annotation here.
    DbService provideDbService() {
        return new DbService();
    }
}
```
**ApplicationComponent.java:**
```
@Singleton
@Component(modules = {ApplicationModule.class, DataModule.class})
public interface ApplicationComponent extends DataComponent{
    void inject(MainApp app);

    @Override
    IDataManager getDataManager();

    @Override
    IDbService exposeDbService();
}
```
**ApplicationModule.java:**
```
@Module
public class ApplicationModule {
    @Provides
    @Singleton
    IDataManager provideDataManager(DataManager dataManager) {
        return dataManager;
    }
}
```
**BaseActivity.java:**
```
    private RealmManager mRealmManager;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        realmManager.openLocalInstance();
        super.onCreate(savedInstanceState);
...
    }

    public void setRealmManager(RealmManager realmManager) {
        mRealmManager = realmManager;
    }

    @Override
    protected void onDestroy() {
        if (mRealmManager != null) {
            mRealmManager.closeLocalInstance();
        }
        super.onDestroy();
    }
```
**Usage:**
**MainActivity.java:**
```
public class MainActivity extends BaseActivity {
    @Inject
    RealmManager realmManager;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getActivityComponent().inject(this);
        setRealmManager(realmManager);
        /////
        getDataManager().getAllBook(realmManager.getLocalInstance());
    }

    @Override
    public void onDestroy() {
        // nothing special is here.
        super.onDestroy();
    }
}
```

**Comment by Zhuinden** [comment]
The introduction of RealmManager allows you to not have to pass in the local Realm instance to the method, but receive it from the RealmManager, without incrementing the reference count.

So DataManager impl can receive the RealmManager, and use `realmManager.getLocalInstance()`.

If the thread where the Realm is used (main thread, background thread) calls `openLocalInstance` and `closeLocalInstance` correctly (where getInstance and close would normally be called), then `getLocalInstance` will work.

**Comment by Zhuinden** [comment]
So just make it singleton and inject it into constructor.

**Comment by Drjacky** [comment]
In the MainActivity, I passed the result of `realmManager.getLocalInstance()` to the `getAllBook` method, cause on a line before it, I passed the Injected RealmManager to the `setRealmManager` function inside BaseActivity, to able to open and close the realm in its `onCreate()` and `onDestroy()`; And avoid write too many `realmManager.openLocalInstance()` and `mRealmManager.closeLocalInstance()` each time on each Activity.
But with your answer, I wasn't able to figure out how to prevent write `openLocalInstance` and `closeLocalInstance` in each activity, **And** satisfy this request
(
```
private void setupSampleView() {
        RealmResults result = mDbService.getAllBooks();
...
}
```
) too.

**Comment by Drjacky** [comment]
Anyway, if we forget about this request (How to prevent write `openLocalInstance` and `closeLocalInstance` in each activity?), and just want to satisfy this request
(`RealmResults result = mDbService.getAllBooks();`),
By your answer(Pass the RealmManager to the DataManager), I couldn't figure out how to do that **And** use DbService too!
So I Inject RealmManager to the DbService, and access to the DbService through DataManager as before; And Inject RealmManager to MainActivity just to call `openLocalInstance()`.
Did I do it right?

**IDbService.java:**
```
public interface IDbService{
    RealmResults<Book> getAllBooks();
}
```
**DbService.java:**
```
public class DbService implements IDbService {
    @Inject
    RealmManager realmManager;

    public DbService() {
   //nothing is here.
    }

    @Override
    public RealmResults<Book> getAllBooks() {
        Realm realm = realmManager.getLocalInstance();
        return realm.allObjects(Book.class);
    }
}
```
**IDataManager.java:**
```
public interface IDataManager extends IDbService {
    @Override
    RealmResults<Book> getAllBooks();
}
```
**DataManager.java:**
```
public class DataManager implements IDataManager{
    private final Context mContext;
    private final IDbService mDbService;

    @Inject
    public DataManager(@ApplicationContext Context context,
                          IDbService dbService) {
        mContext = context;
        mDbService = dbService;
    }

    @Override
    public RealmResults<Book> getAllBooks(); {
        return mDbService.getAllBooks();
    }
}
```
**DataModule.java:**
```
@Module
public class DataModule {

    @Provides
    @Singleton
    RealmManager provideRealmManager(){
        return new RealmManager();
    }

    @Provides
    @Singleton
    IDbService provideIDbService(DbService dbService){
        return DbService;
    }

    @Provides
    @Singleton
    DbService provideDbService() {
        return new DbService();
    }
}
```
**Usage:**
**MainActivity.java:**
```
public class MainActivity extends BaseActivity {

    @Inject
    RealmManager mRealmManager;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        mRealmManager.openLocalInstance(); // I'm not shure about this. But where should I open the database so?
        super.onCreate(savedInstanceState);
        getActivityComponent().inject(this);
        getDataManager().getAllBook();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        realmManager.closeLocalInstance();
    }
}
```

**If I'm doing it in wrong way, please answer by snippet codes.**

**Comment by Zhuinden** [comment]
If the `BaseActivity` calls `openLocalInstance()` and `closeLocalInstance()` on the manager, preferably maybe even before calling `super.onCreate()` in the BaseActivity (so that Realm is open before fragments are re-created), then you wouldn't have to write it in every activity :slightly_smiling_face: 

BTW `allObjects` was removed in like, 0.83.0? Aren't you using latest version (4.2.0)?

**Comment by Zhuinden** [comment]
``` java
public interface IDbService {
    RealmResults<Book> getAllBooks(); // possibly LiveData / Flowable
}
```

DbService.java:

``` java
@Singleton
public class DbService implements IDbService {
    private final RealmManager realmManager;

    @Inject
    public DbService(RealmManager realmManager) {
        this.realmManager = realmManager;
    }

    @Override
    public RealmResults<Book> getAllBooks() {
        Realm realm = realmManager.getLocalInstance();
        return realm.where(Book.class).findAll();
    }
}
```

IDataManager.java:

``` java
public interface IDataManager extends IDbService {
}
```

DataManager.java:

``` java
@Singleton
public class DataManager implements IDataManager {
    private final Context mContext;
    private final IDbService mDbService;

    @Inject
    public DataManager(@ApplicationContext Context context,
                          IDbService dbService) {
        mContext = context;
        mDbService = dbService;
    }

    @Override
    public RealmResults<Book> getAllBooks(); {
        return mDbService.getAllBooks();
    }
}
```

DataModule.java:

``` java
@Module
public class DataModule {
    @Provides
    @Singleton
    RealmManager realmManager(){
        return new RealmManager();
    }

    @Provides
    IDbService provideIDbService(DbService dbService){
        return dbService;
    }
}
```

-----

In your case, I don't really know the difference between a `Service` and a `Manager`.

They kinda do the same thing.

**Comment by Drjacky** [comment]
Thanks. I did what you said. But I have a problem to use RealmManager in the `MainActivity`, to open the Realm.
I get this error:

> Error:(15, 10) error: com.packagename.data.db.RealmManager cannot be provided without an @Inject constructor or from an @Provides- or @Produces-annotated method.
com.packagename.data.db.RealmManager is injected at
com.packagename.ui.main.MainActivity.realmManager
com.packagename.ui.main.MainActivity is injected at
com.packagename.di.component.ActivityComponent.inject(activity)

My Components and Modules:
**ActivityModule**
```javascript
@Module
public class ActivityModule {
    private Activity mActivity;

    public ActivityModule(Activity activity) {
        this.mActivity = activity;
    }

    @Provides
    @ActivityContext
    Context provideContext() {
        return mActivity;
    }

    @Provides
    Activity provideActivity() {
        return mActivity;
    }

    @Provides
    CompositeDisposable provideCompositeDisposable() {
        return new CompositeDisposable();
    }

    @Provides
    SchedulerProvider provideSchedulerProvider() {
        return new AppSchedulerProvider();
    }

    @Provides
    @PerActivity
    MainMvpPresenter<MainMvpView> provideMainPresenter(MainPresenter<MainMvpView>
                                                               presenter) {
        return presenter;
    }
}
```
**ActivityComponent**
```javascript
@PerActivity
@Component(dependencies = ApplicationComponent.class, modules = ActivityModule.class)
public interface ActivityComponent {
    void inject(MainActivity activity);
}
```
**ApplicationModule**
```javascript
@Module
public class ApplicationModule {
    private final Application mApplication;

    public ApplicationModule(Application application) {
        mApplication = application;
    }

    @Provides
    @ApplicationContext
    Context provideContext() {
        return mApplication;
    }

    @Provides
    Application provideApplication() {
        return mApplication;
    }

    @Provides
    @Singleton
    DataManager provideDataManager(AppDataManager appDataManager) {
        return appDataManager;
    }
}
```
**ApplicationComponent**
```javascript
@Singleton
@Component(modules = {ApplicationModule.class, DataModule.class})
public interface ApplicationComponent extends DataComponent{
    void inject(CoreApplication app);

    @ApplicationContext
    Context context();

    Application application();

    DataManager getDataManager();

    @Override
    IDbService exposeIDbService();
}
```
**DataModule**
```javascript
@Module
public class DataModule {
    @Provides
    IDbService provideIDbService(DbService dbService){
        return dbService;
    }

    @Provides
    @Singleton
    RealmManager realmManager(){
        return new RealmManager();
    }
}
```
**DataComponent**
```javascript
@Singleton
public interface DataComponent {
    @Singleton
    IDbService exposeIDbService();
}
```
**CoreApplication**
```javascript
public class CoreApplication extends MultiDexApplication {
    @Inject
    DataManager mDataManager;

    private ApplicationComponent mApplicationComponent;

    @Override
    public void onCreate() {
        super.onCreate();
        setUpRealm();

        mApplicationComponent = DaggerApplicationComponent.builder()
                .applicationModule(new ApplicationModule(this)).build();

        mApplicationComponent.inject(this);
    }

    public ApplicationComponent getApplicationComponent() {
        return mApplicationComponent;
    }

    private void setUpRealm(){
        Realm.init(this);
        RealmConfiguration realmConfiguration = new RealmConfiguration
                .Builder()
                .deleteRealmIfMigrationNeeded()
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);
    }
}
```
**BaseActivity**
```javascript
public class BaseActivity extends AppCompatActivity implements MvpView, BaseFragment.Callback{
    private ActivityComponent mActivityComponent;
    private Unbinder mUnBinder;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        mActivityComponent = DaggerActivityComponent.builder()
                .activityModule(new ActivityModule(this))
                .applicationComponent(((CoreApplication) getApplication()).getApplicationComponent())
                .build();
    }
}
```
_____________________
**Usage:**
**MainActivity**
```javascript
public class MainActivity extends BaseActivityimplements MainMvpView{
    @Inject
    MainMvpPresenter<MainMvpView> mPresenter;

    @Inject
    RealmManager realmManager; //I get the error, because of this line.

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        realmManager.openLocalInstance();
        super.onCreate(savedInstanceState);
        mPresenter.getAllBasket(); //It works, if I able to open the Realm.
    }
}
```
How can I access the RealmManager in MainActivity? (To call `openLocalInstance`). Or even, sometimes maybe I just want to do the DB stuff in MainActivity (Not like now in Presenter via `getDataManager().getAllBasket()`).
**What I missed in the DI?**
Sorry to distributing you.

**Comment by Zhuinden** [comment]
`ApplicationComponent` is missing the provision method `RealmManager realmManager()`, so `ActivityComponent` doesn't see it.

**Comment by Drjacky** [comment]
Now I get NullPointerException on
**MainActivity**
```
    @Inject
    RealmManager realmManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        realmManager.openLocalInstance(); <- NullPointerException!
```

> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.see.app/com.packagename.ui.main.MainActivity}: java.lang.NullPointerException
                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2248)
                                                        at android.app.ActivityThread.access$800(ActivityThread.java:138)
                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                        at android.os.Looper.loop(Looper.java:136)
                                                        at android.app.ActivityThread.main(ActivityThread.java:5111)
                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
                                                        at dalvik.system.NativeStart.main(Native Method)
                                                     Caused by: java.lang.NullPointerException
                                                        at com.packagename.ui.main.MainActivity.onCreate(MainActivity.java:177)

I really appreciate your attention and help :pray:

**Comment by Zhuinden** [comment]
Because `mActivityComponent` would have been initialized by `super.onCreate()`, hmm that makes it tricky, I guess you should just open local instance after `super.onCreate()` then

**Comment by Drjacky** [comment]
That didn't work, unfortunately.
```javascript
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        realmManager.openLocalInstance();
```

**Comment by Zhuinden** [comment]
super.onCreate(savedInstanceState);
        mActivityComponent.inject(this);
        realmManager.openLocalInstance();

**Comment by Drjacky** [comment]
@Zhuinden So it's not possible to prevent write `realmManager.openLocalInstance()` and `realmManager.closeLocalInstance()` each time on each Activity/Fragment but BaseActivity.
Cause with this approach, I get the NullPointerException again:
**BaseActivity**
```javascript
    @Inject
    RealmManager realmManager;

    private ActivityComponent mActivityComponent;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mActivityComponent = DaggerActivityComponent.builder()
                .activityModule(new ActivityModule(this))
                .applicationComponent(((CoreApplication) getApplication()).getApplicationComponent())
                .build();
        realmManager.openLocalInstance(); //<- NullPointerException
    }
```
**MainActivity**
```javascript
public class MainActivity extends BaseActivity implements MainMvpView{
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getActivityComponent().inject(this);
    }
}

```

**Comment by Zhuinden** [comment]
> So it's not possible to prevent write realmManager.openLocalInstance() and realmManager.closeLocalInstance() each time on each Activity/Fragment but BaseActivity.

Actually, you can also inject `BaseActivity`. If you add `void inject(BaseActivity activity)`, it'll inject **only BaseActivity**`, so that would inject the RealmManager field.

Also, don't forget that once you have the component, you can manually obtain scoped `RealmManager` from it with provision method, using `realmManager = mActivityComponent.realmManager();`

**Comment by Zhuinden** [comment]
@Drjacky hello?

**Comment by Drjacky** [comment]
@Zhuinden I'm not in a place where I can test it.
But I will and I'll be sure to tell you and get back to this issue.

**Comment by Zhuinden** [comment]
k

**Comment by Drjacky** [comment]
@Zhuinden When injecting RealmManager into an Adapter, for example like this:
```javascript
public class MainAdapter extends RecyclerView.Adapter<MainAdapter .Viewholder> {
    @Inject
    RealmManager realmManager;
    Realm mRealm;
    Context mContext;

    public MainAdapter (Context ctx, List<Product> product) {
        mContext = ctx;
        ((BaseActivity)mContext).getActivityComponent().inject(this);
        mRealm = realmManager.getLocalInstance();
```
What's happen to the reference count, when there is no `realmManager.closeLocalInstance()` specifically in the Adapter?
Does it count on `MainActivity` which instantiate the `MainAdapter` or on `BaseActivity`? Or neither and there will be an open instance of `realm` at the end?

**Comment by Zhuinden** [comment]
@Drjacky  Did you put `openLocalInstance()` (and `closeLocalInstance()` in your `BaseActivity.onCreate()`?

Because then, `MainAdapter` will use the opened Realm instance that you opened in the Activity, and the ref-count will NOT be increased by the adapter.

**Comment by Drjacky** [comment]
@Zhuinden Yes.
```javascript
public class BaseActivity extends AppCompatActivity {
    @Inject
    RealmManager realmManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mActivityComponent = DaggerActivityComponent.builder()
                .activityModule(new ActivityModule(this))
                .applicationComponent(((CoreApplication) getApplication()).getApplicationComponent())
                .build();
        getActivityComponent().inject(this);
        realmManager.openLocalInstance();
}

    @Override
    protected void onDestroy() {
        super.onDestroy();
        realmManager.closeLocalInstance();
    }
```
Thanks. :pray:

**Comment by Drjacky** [comment]
@Zhuinden What's happen to the reference count, when there is just one `@Inject RealmManager mRealmManager` in `BasicActivity` and the other Activities which extends the BasicActivity use that global `mRealmManager`? :confused:

**Comment by Zhuinden** [comment]
Each base activity calls `openLocalInstance` and `closeLocalInstance` on onCreate/onDestroy which makes it possible to keep it open for as long as needed! 😄 the `get` on UI thread should never return a closed instance for your Activities. 

This is that one thing Realm's default idea got right (the ref counting of a thread)

**Comment by Drjacky** [comment]
Sorry but by 

> Each base activity ...

You mean **Each child activity which extends BasicActivity**?

**Comment by Zhuinden** [comment]
Yes
