### ISSUE TITLE
With the RealmManager, We must not close database manually!

### ISSUE THREAD

**Issue by Drjacky** [Zhuinden/realm-helpers#8]
In the `RealmManager`, we have this:
```javascript
public void closeLocalInstance() {
        checkDefaultConfiguration();
        Realm realm = localRealms.get();
        if(realm == null || realm.isClosed()) {
            throw new IllegalStateException(
                    "Cannot close a Realm that is not open.");
        }
        realm.close();
        // noinspection ConstantConditions
        if(Realm.getLocalInstanceCount(Realm.getDefaultConfiguration()) <= 0) {
            localRealms.set(null);
        }
    }
```
So, when we use try-with-resource, or try-catch-finally (Or in totally, close the opened realm manually), we get the exception:

> Cannot close a Realm that is not open.

Do you think it was better if you removed `throw new IllegalStateException`, and just ignore it?
With the current approach, it's a limitation on try-with-resource usage.
Or totally, you say it's not necessary to use try-catch-finally/try-with-resource in our code, like:
```javascript
Realm realm = null;
    try {
        realm = mRealmManager.getLocalInstance();
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                DBProduct dbProduct = realm.createObject(DBProduct.class, UUID.randomUUID().toString());
                dbProduct.product_id = Product_id;
                if(dbProduct.totalQuantity.get() == null){
                    dbProduct.totalQuantity.set(0);
                    dbProduct.totalQuantity.increment(countOrder);
                }
                else
                    dbProduct.totalQuantity.increment(countOrder);

                DBBasket dbBasket = realm.createObject(DBBasket.class, UUID.randomUUID().toString());
                dbBasket.dbProducts.add(dbProduct);
                dbBasket.totalProducts = numCart;
            }
        });
    } finally {
        if(realm != null) {
            realm.close(); //<- With the RealmManager, we must not use this anymore?
        }
    }
```

**Comment by Zhuinden** [comment]
>             realm.close(); //<- With the RealmManager, we must not use this anymore?

Correct.

Unfortunately you can't try-with-resource on the `openLocalInstance()` call, you need to use `closeLocalInstance()`. 

----

Although now that I've checked the code, I think it could still work if you remove that exception. However, you aren't supposed to call `close` on a Realm instance that you obtained with `getLocalInstance()`, only one that you obtained with `openLocalInstance()`. Otherwise you'll screw up on the ref-counting somewhere (which is why you got the exception above)
